# Build settings for Netlify (root-level for monorepo detection)
[build]
  # Build the frontend workspace explicitly regardless of base dir handling
  command = "npm --prefix frontend install && npm --prefix frontend run build"
  # Publish the built SPA
  publish = "frontend/dist"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:; media-src 'self' https: blob: data: https://*.supabase.co; font-src 'self'; object-src 'none'; frame-src 'none';"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
