# Render.com deployment configuration

# Build command will run npm install automatically
# Start command: npm start

# Environment variables to set in Render dashboard:
# NODE_ENV=production
# DATABASE_URL=your-neon-postgres-url
# JWT_SECRET=your-secure-jwt-secret
# FRONTEND_URL=https://cedistream.onrender.com
# BACKBLAZE_ACCOUNT_ID=your-backblaze-account-id
# BACKBLAZE_APPLICATION_KEY=your-backblaze-application-key
# BACKBLAZE_BUCKET_NAME=cedistream-media
# BACKBLAZE_PUBLIC_BASE=https://s3.eu-central-003.backblazeb2.com
# BACKBLAZE_BUCKET_MEDIA=cedistream-audio-files
# BACKBLAZE_BUCKET_VIDEOS=cedistream-video-files
# BACKBLAZE_BUCKET_PREVIEWS=cedistream-previews
# BACKBLAZE_BUCKET_THUMBNAILS=cedistream-video-thumbnails
# BACKBLAZE_BUCKET_PROFILES=cedistream-profiles
# BACKBLAZE_BUCKET_ALBUMS=cedistream-album-covers
# BACKBLAZE_BUCKET_PROMOTIONS=cedistream-promotions
# PAYSTACK_SECRET_KEY=your-paystack-secret
# PAYSTACK_PUBLIC_KEY=your-paystack-public

# Health check endpoint: /api/health

# Auto-scaling: Minimum 1 instance, maximum 3 instances
# Health check timeout: 30 seconds
# Health check interval: 30 seconds

version: 2

services:
  - type: web
    name: cedistream-backend
    env: node
    region: oregon
    plan: starter
  buildCommand: npm install --omit=dev
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health